imagescripts/launch.sh

As of version 7.1.4, JIRA will show a warning about the database not being configured as recommended. The health check states that the database config is missing settings for `validation-query`, `pool-test-on-borrow` and `pool-test-while-idle`:
For further explanation see the official docs: [How can I resolve this?](https://confluence.atlassian.com/jirakb/health-check-database-connection-settings-792636748.html#HealthCheck:DatabaseConnectionSettings-Resolution)
This patch is based on code from that page and should eliminate the warnings.

Add dbconfig.xml options to stop health warnings

---

Dockerfile

upgrade was required to get through the installation process with postgresql-9.6 as database.

upgraded postgresql jdbc-driver to 9.4.1212

---

Dockerfile

If using docker-compose.yml healthcheck, the normal is to use curl to check app health.
See: https://docs.docker.com/compose/compose-file/#healthcheck

Keep curl package for health-checks

---

imagescripts/common.sh

The session variable for mysql must be default_storage_engine, otherwise it crashes.

storage_engine is deprecated

---

README.md
imagescripts/common.sh
imagescripts/launch.sh

Atlassian has switched the JDBC SQL Server driver they include for JIRA and documented the changes needed (mainly changing the form of the JDBC URL and the Java className of the driver class).  This PR covers adjusting the Docker image to account for these changes.  Additionally this PR includes a fix/enhancement that makes the JDBC connection pool validation query overridable across database versions.
Tested locally using SQL Server 2014
- #72 - Fails for SQL Server (new JDBC driver from Atlassian)

Database connection fixes (SQL Server; Validation query)

---

Dockerfile
README.md
buildscripts/release.sh

- Core/Software: 7.8.1
- Service Desk: 3.11.1
```
```
- https://confluence.atlassian.com/jiracore/issues-resolved-in-7-8-1-947165858.html
- https://confluence.atlassian.com/jirasoftware/issues-resolved-in-7-8-1-947165844.html
- https://confluence.atlassian.com/servicedesk/issues-resolved-in-3-11-1-947165885.html

Bump to Core/Software 7.8.1 and Service Desk 3.11.1

---

Dockerfile

- Dockerize: 0.6.1
- MySQL driver: 5.1.46
```
```
- https://github.com/jwilder/dockerize/releases/tag/v0.6.1
- https://dev.mysql.com/downloads/connector/j/

Bump to Dockerize 0.6.1 and MySQL driver 5.1.46

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.9.0
- Service Desk: 3.12.0
```
```
- Jira: https://confluence.atlassian.com/jirasoftware/jira-software-7-9-x-upgrade-notes-947165815.html
- Service Desk: https://confluence.atlassian.com/servicedesk/jira-service-desk-3-12-x-release-notes-946615993.html

Jira 7.9.0 and Service Desk 3.12.0

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.9.1
- Service Desk: 3.12.1
```
```
- Jira: https://confluence.atlassian.com/jirasoftware/issues-resolved-in-7-9-1-949755869.html
- Service Desk: https://confluence.atlassian.com/servicedesk/issues-resolved-in-3-12-1-949758052.html

Jira 7.9.1 and Service Desk 3.12.1

---

imagescripts/common.sh

Fixing #89 , the error where a slash was missing in url decode. without that %40 will become x40. 
I built a container with the fix and saw the value after url decode to be right
-->

Fixing the urldecode does not replace %40 back to @

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.10.1
- Service Desk: 3.13.1
```
```
- Jira: https://confluence.atlassian.com/jirasoftware/issues-resolved-in-7-10-1-952059662.html
- Service Desk: https://confluence.atlassian.com/servicedesk/issues-resolved-in-3-13-1-952059632.html

Jira 7.10.1 and Service Desk 3.13.1

---

docker-compose.yml

Limit Docker logging. Fixes #92. 
```
```

Fixes #92 - limit Docker logging

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.10.2
- Service Desk: 3.13.2
```
```
- Jira: https://confluence.atlassian.com/jirasoftware/issues-resolved-in-7-10-2-952630071.html
- Service Desk: https://confluence.atlassian.com/servicedesk/issues-resolved-in-3-13-2-952630073.html

Jira 7.10.2 and Service Desk 3.13.2

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.11.0
- Service Desk: 3.14.0
```
```
- Jira: https://confluence.atlassian.com/jirasoftware/jira-software-7-11-x-release-notes-952600888.html
- Service Desk: https://confluence.atlassian.com/servicedesk/jira-service-desk-3-14-x-release-notes-952618829.html

Jira 7.11.0 and Service Desk 3.14.0

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.11.1
- Service Desk: 3.14.1
```
```
- Jira: https://confluence.atlassian.com/jirasoftware/issues-resolved-in-7-11-1-954253993.html
- Service Desk: https://confluence.atlassian.com/servicedesk/issues-resolved-in-3-14-1-954253986.html

Jira 7.11.1 and Service Desk 3.14.1

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.11.2
- Service Desk: 3.14.2
```
```
- Jira: https://confluence.atlassian.com/jirasoftware/jira-software-7-11-x-release-notes-952600888.html
- Service Desk: https://confluence.atlassian.com/servicedesk/jira-service-desk-3-14-x-release-notes-952618829.html

Jira 7.11.2 and Service Desk 3.14.2

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.12.0
- Service Desk: 3.15.0
```
```
- Jira: https://confluence.atlassian.com/jirasoftware/jira-software-7-12-x-release-notes-953676636.html
- Service Desk: https://confluence.atlassian.com/servicedesk/jira-service-desk-3-15-x-release-notes-955163679.html

Jira 7.12.0 and Service Desk 3.15.0

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.12.1
- Service Desk: 3.15.1
```
```
- Jira: https://confluence.atlassian.com/jirasoftware/jira-software-7-12-x-release-notes-953676636.html
- Service Desk: https://confluence.atlassian.com/servicedesk/jira-service-desk-3-15-x-release-notes-955163679.html

Jira 7.12.1 and Service Desk 3.15.1

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.12.2
- Service Desk: 3.15.2
```
```
- Jira: https://confluence.atlassian.com/jirasoftware/jira-software-7-12-x-release-notes-953676636.html
- Service Desk: https://confluence.atlassian.com/servicedesk/jira-service-desk-3-15-x-release-notes-955163679.html

Jira 7.12.2 and Service Desk 3.15.2

---

Dockerfile
README.md
buildscripts/release.sh

- Jira: 7.12.3
- Service Desk: 3.15.3
- Jira: https://confluence.atlassian.com/jirasoftware/jira-software-7-12-x-release-notes-953676636.html
- Service Desk: https://confluence.atlassian.com/servicedesk/jira-service-desk-3-15-x-release-notes-955163679.html

Jira 7.12.3 and Service Desk 3.15.3

---

Dockerfile
README.md
buildscripts/release.sh

* Upgrade to JIRA 7.13.0 and JIRA Service Desk 3.16.0 release.
* Upgrade GLIBC to 2.28-r0 release
* Upgrade MySQL JDBC to 5.1.47
1) Container builds cleanly.
2) JIRA starts up, licence install works and demo project loads.

Upgrade to JIRA 7.13.0 (Enterprise Release)
